// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUe1I1i3sr7p3cCOdfk892lUhkwz2kuaI',
    appId: '1:437422277302:android:a6df8c70724c62dd591c17',
    messagingSenderId: '437422277302',
    projectId: 'project1-ac5cd',
    databaseURL: 'https://project1-ac5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-ac5cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC27sAh9tEvT1hbxPfaqT61A2qQj2ZWVgE',
    appId: '1:437422277302:ios:af2719a1709cce38591c17',
    messagingSenderId: '437422277302',
    projectId: 'project1-ac5cd',
    databaseURL: 'https://project1-ac5cd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project1-ac5cd.appspot.com',
    iosBundleId: 'com.example.kkfinctracker',
  );

}